import type { PlaybookOptionSection } from "../playbookOptions";

export const chosen: PlaybookOptionSection[] = [
  {
    key: "fate",
    label: "Fate",
    description: "Pick how you found out, then two heroic and two doom tags for your fate.",
    kind: "fields",
    fields: [
      {
        key: "found-out",
        label: "How You Found Out",
        kind: "select",
        choices: [
          "Nightmares and visions",
          "Some weirdo told you",
          "An ancient cult found you",
          "Sought out by your nemesis",
          "Attacked by monsters",
          "Trained from birth",
          "You found the prophecy",
        ],
      },
      {
        key: "heroic",
        label: "Heroic tags",
        kind: "multiselect",
        pick: 2,
        choices: [
          "Sacrifice",
          "You are the Champion",
          "Visions",
          "Secret training",
          "Magical powers",
          "Mystical inheritance",
          "A normal life",
          "True love",
          "You can save the world",
          "Hidden allies",
          "The end of monsters",
          "Divine help",
        ],
      },
      {
        key: "doom",
        label: "Doom tags",
        kind: "multiselect",
        pick: 2,
        choices: [
          "Death",
          "You can't save everyone",
          "Impossible love",
          "Failure",
          "A nemesis",
          "No normal life",
          "Loss of loved ones",
          "Treachery",
          "Doubt",
          "Sympathy with the enemy",
          "Damnation",
          "Hosts of monsters",
          "The end of days",
          "The source of Evil",
        ],
      },
    ],
  },
  {
    key: "special-weapon",
    label: "Your Special Weapon",
    description:
      'Design your weapon by choosing a form and three business-end options (added to the base tags), and a material.',
    kind: "fields",
    fields: [
      {
        key: "form",
        label: "Form",
        kind: "select",
        choices: [
          "Staff (1-harm hand/close)",
          "Haft (2-harm hand heavy)",
          "Handle (1-harm hand balanced)",
          "Chain (1-harm hand area)",
        ],
      },
      {
        key: "business-end",
        label: "Business-end (choose 3 options)",
        kind: "multiselect",
        pick: 3,
        choices: [
          'Artifact (add the "magic" tag)',
          'Spikes (+1 harm, add the "messy" tag)',
          "Blade (+1 harm)",
          "Heavy (+1 harm)",
          'Long (add the "close" tag)',
          'Throwable (add the "close" tag)',
          'Chain (add the "area" tag)',
        ],
      },
      {
        key: "material",
        label: "Material",
        kind: "select",
        allowCustom: true,
        choices: ["Steel", "Cold iron", "Silver", "Wood", "Stone", "Bone", "Teeth", "Obsidian"],
      },
    ],
  },
];
