import type { PlaybookOptionSection } from "../playbookOptions";

export const gumshoe: PlaybookOptionSection[] = [
  {
    key: "code",
    label: "Gumshoe Code",
    description:
      "With the agreement of the Keeper, pick a one-sentence Code that your Gumshoe adheres to. Example: Murders must be punished. Monsters must be destroyed. Innocents must be saved. Laws must be enforced. Evil must be exposed. The weak must be protected from the powerful.",
    kind: "fields",
    fields: [
      {
        key: "code",
        label: "Your Code",
        kind: "text",
        placeholder: "e.g. Murders must be punished.",
      },
    ],
  },
  {
    key: "naked-city",
    label: "The Naked City",
    description: "You have lots of personal contacts wherever you go. Pick four contact types.",
    kind: "fields",
    fields: [
      {
        key: "contacts",
        label: "Contact types (pick four)",
        kind: "multiselect",
        pick: 4,
        allowCustom: true,
        choices: [
          "Academics",
          "Accountants",
          "Artists",
          "Bartenders",
          "Clergy",
          "Conspiracy Theorists",
          "Construction",
          "Courts",
          "Criminals (organised)",
          "Criminals (street)",
          "Cultists",
          "Engineers",
          "Espionage",
          "Film and TV",
          "Forensic Scientists",
          "Fringe Scientists",
          "Hackers",
          "Journalists",
          "Lawyers",
          "Mechanics",
          "Media",
          "Medical Practitioners",
          "Military",
          "Morgue",
          "Occult",
          "Police (local)",
          "Police (national)",
          "Politicians",
          "Prisons",
          "Private Security",
          "Property Developers",
          "Stage Magicians",
          "Technologists",
          "Transportation",
        ],
      },
    ],
  },
];
